import type { SQLiteDatabase } from 'expo-sqlite';

import type { ExerciseGifKey } from '@/assets/assets_index';

import type { ExerciseCategory, TrackType } from './types';

const SEED_TIMESTAMP = '2026-01-01T00:00:00.000Z';

type SeedExercise = {
  id: ExerciseGifKey;
  slug: ExerciseGifKey;
  asset_key: ExerciseGifKey;
  name: string;
  category: ExerciseCategory;
  primary_muscle: string;
  secondary_muscles: string[];
  track_type: TrackType;
  instructions: string;
};

export const EXERCISE_SEEDS = [
  {
    id: 'chest_press',
    slug: 'chest_press',
    asset_key: 'chest_press',
    name: 'Chest Press',
    category: 'machine',
    primary_muscle: 'chest',
    secondary_muscles: ['triceps', 'front_delts'],
    track_type: 'weight_reps',
    instructions: 'Press forward with control and keep the shoulder blades stable.',
  },
  {
    id: 'incline_chest_press',
    slug: 'incline_chest_press',
    asset_key: 'incline_chest_press',
    name: 'Incline Chest Press',
    category: 'machine',
    primary_muscle: 'upper_chest',
    secondary_muscles: ['triceps', 'front_delts'],
    track_type: 'weight_reps',
    instructions: 'Drive upward on the incline path without shrugging the shoulders.',
  },
  {
    id: 'pec_deck',
    slug: 'pec_deck',
    asset_key: 'pec_deck',
    name: 'Pec Deck',
    category: 'machine',
    primary_muscle: 'chest',
    secondary_muscles: ['front_delts'],
    track_type: 'weight_reps',
    instructions: 'Bring the handles together with a soft bend in the elbows.',
  },
  {
    id: 'lat_pulldown',
    slug: 'lat_pulldown',
    asset_key: 'lat_pulldown',
    name: 'Lat Pulldown',
    category: 'machine',
    primary_muscle: 'lats',
    secondary_muscles: ['biceps', 'upper_back'],
    track_type: 'weight_reps',
    instructions: 'Pull the bar toward the upper chest and keep the torso steady.',
  },
  {
    id: 'seated_row',
    slug: 'seated_row',
    asset_key: 'seated_row',
    name: 'Seated Row',
    category: 'machine',
    primary_muscle: 'mid_back',
    secondary_muscles: ['lats', 'biceps'],
    track_type: 'weight_reps',
    instructions: 'Row toward the torso and pause briefly with the shoulder blades back.',
  },
  {
    id: 'assisted_pull_up',
    slug: 'assisted_pull_up',
    asset_key: 'assisted_pull_up',
    name: 'Assisted Pull Up',
    category: 'machine',
    primary_muscle: 'lats',
    secondary_muscles: ['biceps', 'mid_back'],
    track_type: 'weight_reps',
    instructions: 'Use only enough assistance to move through the full range.',
  },
  {
    id: 'shoulder_press',
    slug: 'shoulder_press',
    asset_key: 'shoulder_press',
    name: 'Shoulder Press',
    category: 'machine',
    primary_muscle: 'shoulders',
    secondary_muscles: ['triceps', 'upper_chest'],
    track_type: 'weight_reps',
    instructions: 'Press overhead while keeping ribs down and wrists stacked.',
  },
  {
    id: 'lateral_raise',
    slug: 'lateral_raise',
    asset_key: 'lateral_raise',
    name: 'Lateral Raise',
    category: 'machine',
    primary_muscle: 'side_delts',
    secondary_muscles: ['traps'],
    track_type: 'weight_reps',
    instructions: 'Raise to shoulder height with slow control and minimal momentum.',
  },
  {
    id: 'rear_delt_fly',
    slug: 'rear_delt_fly',
    asset_key: 'rear_delt_fly',
    name: 'Rear Delt Fly',
    category: 'machine',
    primary_muscle: 'rear_delts',
    secondary_muscles: ['upper_back'],
    track_type: 'weight_reps',
    instructions: 'Open the arms wide and keep the neck relaxed.',
  },
  {
    id: 'triceps_pushdown',
    slug: 'triceps_pushdown',
    asset_key: 'triceps_pushdown',
    name: 'Triceps Pushdown',
    category: 'machine',
    primary_muscle: 'triceps',
    secondary_muscles: [],
    track_type: 'weight_reps',
    instructions: 'Keep elbows pinned and finish with a full triceps squeeze.',
  },
  {
    id: 'overhead_triceps_extension',
    slug: 'overhead_triceps_extension',
    asset_key: 'overhead_triceps_extension',
    name: 'Overhead Triceps Extension',
    category: 'machine',
    primary_muscle: 'triceps',
    secondary_muscles: ['core'],
    track_type: 'weight_reps',
    instructions: 'Extend overhead without flaring the ribs or moving the elbows forward.',
  },
  {
    id: 'biceps_curl_machine',
    slug: 'biceps_curl_machine',
    asset_key: 'biceps_curl_machine',
    name: 'Biceps Curl Machine',
    category: 'machine',
    primary_muscle: 'biceps',
    secondary_muscles: ['forearms'],
    track_type: 'weight_reps',
    instructions: 'Curl smoothly and avoid lifting the elbows from the pad.',
  },
  {
    id: 'cable_curl',
    slug: 'cable_curl',
    asset_key: 'cable_curl',
    name: 'Cable Curl',
    category: 'machine',
    primary_muscle: 'biceps',
    secondary_muscles: ['forearms'],
    track_type: 'weight_reps',
    instructions: 'Keep constant cable tension through the full curl.',
  },
  {
    id: 'barbell_squat',
    slug: 'barbell_squat',
    asset_key: 'barbell_squat',
    name: 'Barbell Squat',
    category: 'free_weight',
    primary_muscle: 'quads',
    secondary_muscles: ['glutes', 'hamstrings', 'core'],
    track_type: 'weight_reps',
    instructions: 'Brace, descend under control, and drive through the midfoot.',
  },
  {
    id: 'leg_press',
    slug: 'leg_press',
    asset_key: 'leg_press',
    name: 'Leg Press',
    category: 'machine',
    primary_muscle: 'quads',
    secondary_muscles: ['glutes', 'hamstrings'],
    track_type: 'weight_reps',
    instructions: 'Lower the sled with control and avoid locking the knees hard.',
  },
  {
    id: 'leg_extension',
    slug: 'leg_extension',
    asset_key: 'leg_extension',
    name: 'Leg Extension',
    category: 'machine',
    primary_muscle: 'quads',
    secondary_muscles: [],
    track_type: 'weight_reps',
    instructions: 'Extend the knees and pause briefly at the top.',
  },
  {
    id: 'seated_leg_curl',
    slug: 'seated_leg_curl',
    asset_key: 'seated_leg_curl',
    name: 'Seated Leg Curl',
    category: 'machine',
    primary_muscle: 'hamstrings',
    secondary_muscles: ['calves'],
    track_type: 'weight_reps',
    instructions: 'Curl down with control and keep hips pressed into the pad.',
  },
  {
    id: 'lying_leg_curl',
    slug: 'lying_leg_curl',
    asset_key: 'lying_leg_curl',
    name: 'Lying Leg Curl',
    category: 'machine',
    primary_muscle: 'hamstrings',
    secondary_muscles: ['calves'],
    track_type: 'weight_reps',
    instructions: 'Curl toward the glutes without arching the lower back.',
  },
  {
    id: 'hip_abduction',
    slug: 'hip_abduction',
    asset_key: 'hip_abduction',
    name: 'Hip Abduction',
    category: 'machine',
    primary_muscle: 'glutes',
    secondary_muscles: ['hips'],
    track_type: 'weight_reps',
    instructions: 'Open the knees outward and control the return.',
  },
  {
    id: 'hip_adduction',
    slug: 'hip_adduction',
    asset_key: 'hip_adduction',
    name: 'Hip Adduction',
    category: 'machine',
    primary_muscle: 'adductors',
    secondary_muscles: ['hips'],
    track_type: 'weight_reps',
    instructions: 'Bring the knees together under control and avoid bouncing.',
  },
  {
    id: 'calf_raise',
    slug: 'calf_raise',
    asset_key: 'calf_raise',
    name: 'Calf Raise',
    category: 'machine',
    primary_muscle: 'calves',
    secondary_muscles: [],
    track_type: 'weight_reps',
    instructions: 'Rise fully onto the toes and lower to a controlled stretch.',
  },
  {
    id: 'romanian_deadlift',
    slug: 'romanian_deadlift',
    asset_key: 'romanian_deadlift',
    name: 'Romanian Deadlift',
    category: 'free_weight',
    primary_muscle: 'hamstrings',
    secondary_muscles: ['glutes', 'lower_back'],
    track_type: 'weight_reps',
    instructions: 'Hinge at the hips and keep the bar close to the legs.',
  },
  {
    id: 'dumbbell_bench_press',
    slug: 'dumbbell_bench_press',
    asset_key: 'dumbbell_bench_press',
    name: 'Dumbbell Bench Press',
    category: 'free_weight',
    primary_muscle: 'chest',
    secondary_muscles: ['triceps', 'front_delts'],
    track_type: 'weight_reps',
    instructions: 'Press both dumbbells evenly and keep wrists over elbows.',
  },
  {
    id: 'dumbbell_row',
    slug: 'dumbbell_row',
    asset_key: 'dumbbell_row',
    name: 'Dumbbell Row',
    category: 'free_weight',
    primary_muscle: 'lats',
    secondary_muscles: ['biceps', 'mid_back'],
    track_type: 'weight_reps',
    instructions: 'Row toward the hip and avoid rotating the torso.',
  },
  {
    id: 'dumbbell_shoulder_press',
    slug: 'dumbbell_shoulder_press',
    asset_key: 'dumbbell_shoulder_press',
    name: 'Dumbbell Shoulder Press',
    category: 'free_weight',
    primary_muscle: 'shoulders',
    secondary_muscles: ['triceps'],
    track_type: 'weight_reps',
    instructions: 'Press overhead in a stable path without leaning back.',
  },
  {
    id: 'dumbbell_lateral_raise',
    slug: 'dumbbell_lateral_raise',
    asset_key: 'dumbbell_lateral_raise',
    name: 'Dumbbell Lateral Raise',
    category: 'free_weight',
    primary_muscle: 'side_delts',
    secondary_muscles: ['traps'],
    track_type: 'weight_reps',
    instructions: 'Lead with the elbows and stop near shoulder height.',
  },
  {
    id: 'dumbbell_curl',
    slug: 'dumbbell_curl',
    asset_key: 'dumbbell_curl',
    name: 'Dumbbell Curl',
    category: 'free_weight',
    primary_muscle: 'biceps',
    secondary_muscles: ['forearms'],
    track_type: 'weight_reps',
    instructions: 'Curl without swinging and lower slowly.',
  },
  {
    id: 'hammer_curl',
    slug: 'hammer_curl',
    asset_key: 'hammer_curl',
    name: 'Hammer Curl',
    category: 'free_weight',
    primary_muscle: 'biceps',
    secondary_muscles: ['forearms', 'brachialis'],
    track_type: 'weight_reps',
    instructions: 'Keep palms facing each other and control the descent.',
  },
  {
    id: 'plank',
    slug: 'plank',
    asset_key: 'plank',
    name: 'Plank',
    category: 'bodyweight',
    primary_muscle: 'core',
    secondary_muscles: ['shoulders', 'glutes'],
    track_type: 'duration_only',
    instructions: 'Hold a straight line from head to heels while breathing steadily.',
  },
  {
    id: 'crunch',
    slug: 'crunch',
    asset_key: 'crunch',
    name: 'Crunch',
    category: 'bodyweight',
    primary_muscle: 'abs',
    secondary_muscles: [],
    track_type: 'weight_reps',
    instructions: 'Curl the upper back off the floor without pulling the neck.',
  },
  {
    id: 'hanging_knee_raise',
    slug: 'hanging_knee_raise',
    asset_key: 'hanging_knee_raise',
    name: 'Hanging Knee Raise',
    category: 'bodyweight',
    primary_muscle: 'abs',
    secondary_muscles: ['hip_flexors'],
    track_type: 'weight_reps',
    instructions: 'Raise the knees with control and limit swinging.',
  },
  {
    id: 'treadmill',
    slug: 'treadmill',
    asset_key: 'treadmill',
    name: 'Treadmill',
    category: 'cardio',
    primary_muscle: 'cardio',
    secondary_muscles: ['quads', 'hamstrings', 'calves'],
    track_type: 'distance_duration_incline',
    instructions: 'Track distance, duration, and incline for each effort.',
  },
  {
    id: 'interval_run',
    slug: 'interval_run',
    asset_key: 'interval_run',
    name: 'Interval Run',
    category: 'cardio',
    primary_muscle: 'cardio',
    secondary_muscles: ['quads', 'hamstrings', 'calves'],
    track_type: 'distance_duration_incline',
    instructions: 'Record the interval distance, incline, and total work duration.',
  },
  {
    id: 'stationary_bike',
    slug: 'stationary_bike',
    asset_key: 'stationary_bike',
    name: 'Stationary Bike',
    category: 'cardio',
    primary_muscle: 'cardio',
    secondary_muscles: ['quads', 'glutes'],
    track_type: 'duration_only',
    instructions: 'Track duration for steady bike work.',
  },
  {
    id: 'elliptical',
    slug: 'elliptical',
    asset_key: 'elliptical',
    name: 'Elliptical',
    category: 'cardio',
    primary_muscle: 'cardio',
    secondary_muscles: ['quads', 'glutes', 'calves'],
    track_type: 'distance_duration_incline',
    instructions: 'Track distance, duration, and ramp or incline level.',
  },
  {
    id: 'rowing_machine',
    slug: 'rowing_machine',
    asset_key: 'rowing_machine',
    name: 'Rowing Machine',
    category: 'cardio',
    primary_muscle: 'cardio',
    secondary_muscles: ['back', 'legs', 'arms'],
    track_type: 'duration_only',
    instructions: 'Track duration for rowing intervals or steady work.',
  },
  {
    id: 'stair_climber',
    slug: 'stair_climber',
    asset_key: 'stair_climber',
    name: 'Stair Climber',
    category: 'cardio',
    primary_muscle: 'cardio',
    secondary_muscles: ['glutes', 'quads', 'calves'],
    track_type: 'duration_only',
    instructions: 'Track duration and keep posture tall during the climb.',
  },
] as const satisfies readonly SeedExercise[];

export const SEEDED_EXERCISE_COUNT = EXERCISE_SEEDS.length;

const UPSERT_EXERCISE_SQL = `
INSERT INTO exercises (
  id,
  slug,
  asset_key,
  name,
  category,
  primary_muscle,
  secondary_muscles,
  track_type,
  instructions,
  created_at,
  updated_at,
  deleted_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, NULL)
ON CONFLICT(id) DO UPDATE SET
  slug = excluded.slug,
  asset_key = excluded.asset_key,
  name = excluded.name,
  category = excluded.category,
  primary_muscle = excluded.primary_muscle,
  secondary_muscles = excluded.secondary_muscles,
  track_type = excluded.track_type,
  instructions = excluded.instructions,
  updated_at = excluded.updated_at,
  deleted_at = NULL;
`;

export async function seedDatabase(database: SQLiteDatabase): Promise<void> {
  await database.withTransactionAsync(async () => {
    for (const exercise of EXERCISE_SEEDS) {
      await database.runAsync(
        UPSERT_EXERCISE_SQL,
        exercise.id,
        exercise.slug,
        exercise.asset_key,
        exercise.name,
        exercise.category,
        exercise.primary_muscle,
        JSON.stringify(exercise.secondary_muscles),
        exercise.track_type,
        exercise.instructions,
        SEED_TIMESTAMP,
        SEED_TIMESTAMP,
      );
    }
  });
}
